version: "3"
services:
    db:
        image: postgres:12.4
        ports:
            - 5433:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgress
            - POSTGRES_DB=funcss
        volumes: 
            - ./data_funcss:/var/lib/postgresql/data